ARG ELASTIC_VERSION
ARG ELASTIC_SOURCE
# https://www.docker.elastic.co/
FROM ${ELASTIC_SOURCE}:${ELASTIC_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
