ARG ELASTIC_VERSION
ARG LOGSTASH_SOURCE
# https://www.docker.elastic.co/
FROM ${LOGSTASH_SOURCE}:${ELASTIC_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
